import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'pt' | 'fr' | 'es' | 'zh';

export const languageNames: Record<Language, string> = {
  en: 'English',
  pt: 'Português',
  fr: 'Français',
  es: 'Español',
  zh: '中文',
};

const translations = {
  en: {
    viewBookingPage: '↗ View booking page',
    signOut: 'Sign out',
    tabs: {
      bookings: 'Bookings',
      services: 'Services',
      availability: 'Availability',
      billing: 'Billing',
    },
    availability: {
      title: 'Availability',
      subtitle: 'Set which days and hours your business is open for bookings.',
      closed: 'Closed',
      to: 'to',
      save: 'Save schedule',
      saving: 'Saving…',
      saved: '✓ Saved!',
      saveError: 'Failed to save. Please try again.',
      days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: 'Choose a service',
      chooseDate: 'Choose a date',
      chooseTime: 'Choose a time',
      confirmBooking: 'Confirm booking',
      back: '← Back',
      today: 'Today',
      min: 'min',
      checkingAvailability: 'Checking availability…',
      noAvailability: 'No availability',
      tryAnotherDate: 'Try another date.',
      chooseAnotherDate: '← Choose another date',
      notes: 'Notes (optional)',
      notesPlaceholder: 'Any info for the business…',
      signInNotice: "You'll be asked to sign in or create an account to confirm this booking.",
      confirmBtn: 'Confirm booking →',
      signInConfirmBtn: 'Sign in & confirm →',
      bookingInProgress: 'Booking…',
      service: 'Service',
      date: 'Date',
      time: 'Time',
      duration: 'Duration',
      total: 'Total',
      allBooked: 'All booked!',
      bookAgain: 'Book again',
      viewMyBookings: 'View my bookings →',
      bookedSoon: 'The business will confirm your appointment shortly.',
    },
    client: {
      hi: 'Hi,',
      upcomingBookings: 'Your upcoming and past bookings.',
    },
    loading: 'Loading…',
  },
  pt: {
    viewBookingPage: '↗ Ver página de agendamento',
    signOut: 'Sair',
    tabs: {
      bookings: 'Agendamentos',
      services: 'Serviços',
      availability: 'Disponibilidade',
      billing: 'Faturação',
    },
    availability: {
      title: 'Disponibilidade',
      subtitle: 'Defina os dias e horários em que o seu negócio aceita agendamentos.',
      closed: 'Fechado',
      to: 'às',
      save: 'Guardar horário',
      saving: 'A guardar…',
      saved: '✓ Guardado!',
      saveError: 'Falha ao guardar. Tente novamente.',
      days: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: 'Escolha um serviço',
      chooseDate: 'Escolha uma data',
      chooseTime: 'Escolha um horário',
      confirmBooking: 'Confirmar agendamento',
      back: '← Voltar',
      today: 'Hoje',
      min: 'min',
      checkingAvailability: 'A verificar disponibilidade…',
      noAvailability: 'Sem disponibilidade',
      tryAnotherDate: 'Tente outra data.',
      chooseAnotherDate: '← Escolher outra data',
      notes: 'Notas (opcional)',
      notesPlaceholder: 'Informação para o negócio…',
      signInNotice: 'Será pedido para iniciar sessão ou criar uma conta para confirmar este agendamento.',
      confirmBtn: 'Confirmar agendamento →',
      signInConfirmBtn: 'Iniciar sessão e confirmar →',
      bookingInProgress: 'A agendar…',
      service: 'Serviço',
      date: 'Data',
      time: 'Hora',
      duration: 'Duração',
      total: 'Total',
      allBooked: 'Tudo agendado!',
      bookAgain: 'Agendar novamente',
      viewMyBookings: 'Ver os meus agendamentos →',
      bookedSoon: 'O negócio irá confirmar o seu agendamento em breve.',
    },
    client: {
      hi: 'Olá,',
      upcomingBookings: 'Os seus agendamentos futuros e passados.',
    },
    loading: 'A carregar…',
  },
  fr: {
    viewBookingPage: '↗ Voir la page de réservation',
    signOut: 'Se déconnecter',
    tabs: {
      bookings: 'Réservations',
      services: 'Services',
      availability: 'Disponibilité',
      billing: 'Facturation',
    },
    availability: {
      title: 'Disponibilité',
      subtitle: "Définissez les jours et heures d'ouverture de votre entreprise.",
      closed: 'Fermé',
      to: 'à',
      save: 'Enregistrer les horaires',
      saving: 'Enregistrement…',
      saved: '✓ Enregistré !',
      saveError: "Échec de l'enregistrement. Veuillez réessayer.",
      days: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: 'Choisir un service',
      chooseDate: 'Choisir une date',
      chooseTime: 'Choisir un horaire',
      confirmBooking: 'Confirmer la réservation',
      back: '← Retour',
      today: "Aujourd'hui",
      min: 'min',
      checkingAvailability: 'Vérification des disponibilités…',
      noAvailability: 'Pas de disponibilité',
      tryAnotherDate: 'Essayez une autre date.',
      chooseAnotherDate: '← Choisir une autre date',
      notes: 'Notes (facultatif)',
      notesPlaceholder: "Informations pour l'entreprise…",
      signInNotice: 'Vous devrez vous connecter ou créer un compte pour confirmer cette réservation.',
      confirmBtn: 'Confirmer la réservation →',
      signInConfirmBtn: 'Se connecter et confirmer →',
      bookingInProgress: 'Réservation…',
      service: 'Service',
      date: 'Date',
      time: 'Heure',
      duration: 'Durée',
      total: 'Total',
      allBooked: 'Réservé !',
      bookAgain: 'Réserver à nouveau',
      viewMyBookings: 'Voir mes réservations →',
      bookedSoon: "L'entreprise confirmera votre rendez-vous prochainement.",
    },
    client: {
      hi: 'Bonjour,',
      upcomingBookings: 'Vos réservations à venir et passées.',
    },
    loading: 'Chargement…',
  },
  es: {
    viewBookingPage: '↗ Ver página de reservas',
    signOut: 'Cerrar sesión',
    tabs: {
      bookings: 'Reservas',
      services: 'Servicios',
      availability: 'Disponibilidad',
      billing: 'Facturación',
    },
    availability: {
      title: 'Disponibilidad',
      subtitle: 'Establezca los días y horarios en que su negocio acepta reservas.',
      closed: 'Cerrado',
      to: 'a',
      save: 'Guardar horario',
      saving: 'Guardando…',
      saved: '✓ ¡Guardado!',
      saveError: 'Error al guardar. Inténtelo de nuevo.',
      days: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: 'Elegir un servicio',
      chooseDate: 'Elegir una fecha',
      chooseTime: 'Elegir un horario',
      confirmBooking: 'Confirmar reserva',
      back: '← Volver',
      today: 'Hoy',
      min: 'min',
      checkingAvailability: 'Comprobando disponibilidad…',
      noAvailability: 'Sin disponibilidad',
      tryAnotherDate: 'Pruebe otra fecha.',
      chooseAnotherDate: '← Elegir otra fecha',
      notes: 'Notas (opcional)',
      notesPlaceholder: 'Información para el negocio…',
      signInNotice: 'Se le pedirá que inicie sesión o cree una cuenta para confirmar esta reserva.',
      confirmBtn: 'Confirmar reserva →',
      signInConfirmBtn: 'Iniciar sesión y confirmar →',
      bookingInProgress: 'Reservando…',
      service: 'Servicio',
      date: 'Fecha',
      time: 'Hora',
      duration: 'Duración',
      total: 'Total',
      allBooked: '¡Reservado!',
      bookAgain: 'Reservar de nuevo',
      viewMyBookings: 'Ver mis reservas →',
      bookedSoon: 'El negocio confirmará su cita en breve.',
    },
    client: {
      hi: 'Hola,',
      upcomingBookings: 'Sus próximas reservas y las pasadas.',
    },
    loading: 'Cargando…',
  },
  zh: {
    viewBookingPage: '↗ 查看预约页面',
    signOut: '退出登录',
    tabs: {
      bookings: '预约',
      services: '服务',
      availability: '可用时间',
      billing: '账单',
    },
    availability: {
      title: '可用时间',
      subtitle: '设置您的业务接受预约的日期和时间。',
      closed: '关闭',
      to: '至',
      save: '保存时间表',
      saving: '保存中…',
      saved: '✓ 已保存！',
      saveError: '保存失败，请重试。',
      days: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: '选择服务',
      chooseDate: '选择日期',
      chooseTime: '选择时间',
      confirmBooking: '确认预约',
      back: '← 返回',
      today: '今天',
      min: '分钟',
      checkingAvailability: '检查可用性…',
      noAvailability: '无可用时间',
      tryAnotherDate: '请尝试其他日期。',
      chooseAnotherDate: '← 选择其他日期',
      notes: '备注（可选）',
      notesPlaceholder: '给商家的信息…',
      signInNotice: '您需要登录或创建账户以确认预约。',
      confirmBtn: '确认预约 →',
      signInConfirmBtn: '登录并确认 →',
      bookingInProgress: '预约中…',
      service: '服务',
      date: '日期',
      time: '时间',
      duration: '时长',
      total: '合计',
      allBooked: '预约成功！',
      bookAgain: '再次预约',
      viewMyBookings: '查看我的预约 →',
      bookedSoon: '商家将很快确认您的预约。',
    },
    client: {
      hi: '你好，',
      upcomingBookings: '您即将到来的和过去的预约。',
    },
    loading: '加载中…',
  },
};

export type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: translations.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
