import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'pt' | 'fr' | 'es' | 'zh';

export const languageNames: Record<Language, string> = {
  en: 'English',
  pt: 'Português',
  fr: 'Français',
  es: 'Español',
  zh: '中文',
};

const translations = {
  en: {
    loading: 'Loading…',
    viewBookingPage: '↗ View booking page',
    signOut: 'Sign out',
    tabs: {
      bookings: 'Bookings',
      services: 'Services',
      availability: 'Availability',
      billing: 'Billing',
    },
    availability: {
      title: 'Availability',
      subtitle: 'Set which days and hours your business is open for bookings.',
      closed: 'Closed',
      to: 'to',
      save: 'Save schedule',
      saving: 'Saving…',
      saved: '✓ Saved!',
      saveError: 'Failed to save. Please try again.',
      days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    services: {
      title: 'Services',
      subtitle: 'Define what you offer and how long each takes.',
      add: '+ Add service',
      editTitle: 'Edit service',
      newTitle: 'New service',
      empty: 'No services yet',
      emptyHint: 'Add your first service to start accepting bookings.',
      nameLabel: 'Service name',
      namePlaceholder: 'Haircut & Styling',
      descLabel: 'Description (optional)',
      descPlaceholder: 'A short description for your clients…',
      durationLabel: 'Duration (minutes)',
      priceLabel: 'Price (€)',
      saveChanges: 'Save changes',
      create: 'Create service',
      cancel: 'Cancel',
      edit: 'Edit',
      remove: 'Remove',
      removeConfirm: 'Remove this service?',
      saving: 'Saving…',
    },
    bookings: {
      title: 'Bookings',
      subtitle: 'All client appointments for your business.',
      empty: 'No bookings yet',
      emptyHint: 'Share your booking link to start receiving appointments.',
      all: 'all',
      pending: 'pending',
      confirmed: 'confirmed',
      cancelled: 'cancelled',
      confirm: 'Confirm',
      cancel: 'Cancel',
    },
    clientBookings: {
      empty: 'No bookings yet',
      emptyHint: 'Find a business and make your first appointment.',
      bookAgain: 'Book again →',
    },
    billing: {
      title: 'Billing',
      subtitle: 'Manage your subscription and plan.',
      successBanner: 'Subscription activated! Your plan has been upgraded to Pro.',
      cancelledBanner: 'Checkout cancelled. No changes were made.',
      current: 'current',
      freeFeature1: '1 business',
      freeFeature2: 'Up to 50 bookings/mo',
      freeFeature3: 'Basic availability',
      proFeature1: 'Unlimited bookings',
      proFeature2: 'Email notifications',
      proFeature3: 'Priority support',
      upgrade: 'Upgrade to Pro',
      manageBilling: 'Manage billing',
      loadingBtn: 'Loading…',
      cancelHint: 'To cancel or change your subscription, use the billing portal above.',
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: 'Choose a service',
      chooseDate: 'Choose a date',
      chooseTime: 'Choose a time',
      confirmBooking: 'Confirm booking',
      back: '← Back',
      today: 'Today',
      min: 'min',
      checkingAvailability: 'Checking availability…',
      noAvailability: 'No availability',
      tryAnotherDate: 'Try another date.',
      chooseAnotherDate: '← Choose another date',
      notes: 'Notes (optional)',
      notesPlaceholder: 'Any info for the business…',
      signInNotice: "You'll be asked to sign in or create an account to confirm this booking.",
      confirmBtn: 'Confirm booking →',
      signInConfirmBtn: 'Sign in & confirm →',
      bookingInProgress: 'Booking…',
      service: 'Service',
      date: 'Date',
      time: 'Time',
      duration: 'Duration',
      total: 'Total',
      allBooked: 'All booked!',
      bookAgain: 'Book again',
      viewMyBookings: 'View my bookings →',
      bookedSoon: 'The business will confirm your appointment shortly.',
    },
    client: {
      hi: 'Hi,',
      upcomingBookings: 'Your upcoming and past bookings.',
    },
  },

  pt: {
    loading: 'A carregar…',
    viewBookingPage: '↗ Ver página de agendamento',
    signOut: 'Sair',
    tabs: {
      bookings: 'Agendamentos',
      services: 'Serviços',
      availability: 'Disponibilidade',
      billing: 'Faturação',
    },
    availability: {
      title: 'Disponibilidade',
      subtitle: 'Defina os dias e horários em que o seu negócio aceita agendamentos.',
      closed: 'Fechado',
      to: 'às',
      save: 'Guardar horário',
      saving: 'A guardar…',
      saved: '✓ Guardado!',
      saveError: 'Falha ao guardar. Tente novamente.',
      days: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    },
    services: {
      title: 'Serviços',
      subtitle: 'Defina o que oferece e quanto tempo cada serviço demora.',
      add: '+ Adicionar serviço',
      editTitle: 'Editar serviço',
      newTitle: 'Novo serviço',
      empty: 'Nenhum serviço ainda',
      emptyHint: 'Adicione o seu primeiro serviço para começar a receber agendamentos.',
      nameLabel: 'Nome do serviço',
      namePlaceholder: 'Corte & Styling',
      descLabel: 'Descrição (opcional)',
      descPlaceholder: 'Uma breve descrição para os seus clientes…',
      durationLabel: 'Duração (minutos)',
      priceLabel: 'Preço (€)',
      saveChanges: 'Guardar alterações',
      create: 'Criar serviço',
      cancel: 'Cancelar',
      edit: 'Editar',
      remove: 'Remover',
      removeConfirm: 'Remover este serviço?',
      saving: 'A guardar…',
    },
    bookings: {
      title: 'Agendamentos',
      subtitle: 'Todos os agendamentos dos seus clientes.',
      empty: 'Nenhum agendamento ainda',
      emptyHint: 'Partilhe o seu link de agendamento para começar a receber marcações.',
      all: 'todos',
      pending: 'pendente',
      confirmed: 'confirmado',
      cancelled: 'cancelado',
      confirm: 'Confirmar',
      cancel: 'Cancelar',
    },
    clientBookings: {
      empty: 'Nenhum agendamento ainda',
      emptyHint: 'Encontre um negócio e faça a sua primeira marcação.',
      bookAgain: 'Agendar novamente →',
    },
    billing: {
      title: 'Faturação',
      subtitle: 'Gerencie a sua subscrição e plano.',
      successBanner: 'Subscrição ativada! O seu plano foi atualizado para Pro.',
      cancelledBanner: 'Checkout cancelado. Nenhuma alteração foi feita.',
      current: 'atual',
      freeFeature1: '1 negócio',
      freeFeature2: 'Até 50 agendamentos/mês',
      freeFeature3: 'Disponibilidade básica',
      proFeature1: 'Agendamentos ilimitados',
      proFeature2: 'Notificações por email',
      proFeature3: 'Suporte prioritário',
      upgrade: 'Atualizar para Pro',
      manageBilling: 'Gerir faturação',
      loadingBtn: 'A carregar…',
      cancelHint: 'Para cancelar ou alterar a sua subscrição, use o portal de faturação acima.',
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: 'Escolha um serviço',
      chooseDate: 'Escolha uma data',
      chooseTime: 'Escolha um horário',
      confirmBooking: 'Confirmar agendamento',
      back: '← Voltar',
      today: 'Hoje',
      min: 'min',
      checkingAvailability: 'A verificar disponibilidade…',
      noAvailability: 'Sem disponibilidade',
      tryAnotherDate: 'Tente outra data.',
      chooseAnotherDate: '← Escolher outra data',
      notes: 'Notas (opcional)',
      notesPlaceholder: 'Informação para o negócio…',
      signInNotice: 'Será pedido para iniciar sessão ou criar uma conta para confirmar este agendamento.',
      confirmBtn: 'Confirmar agendamento →',
      signInConfirmBtn: 'Iniciar sessão e confirmar →',
      bookingInProgress: 'A agendar…',
      service: 'Serviço',
      date: 'Data',
      time: 'Hora',
      duration: 'Duração',
      total: 'Total',
      allBooked: 'Tudo agendado!',
      bookAgain: 'Agendar novamente',
      viewMyBookings: 'Ver os meus agendamentos →',
      bookedSoon: 'O negócio irá confirmar o seu agendamento em breve.',
    },
    client: {
      hi: 'Olá,',
      upcomingBookings: 'Os seus agendamentos futuros e passados.',
    },
  },

  fr: {
    loading: 'Chargement…',
    viewBookingPage: '↗ Voir la page de réservation',
    signOut: 'Se déconnecter',
    tabs: {
      bookings: 'Réservations',
      services: 'Services',
      availability: 'Disponibilité',
      billing: 'Facturation',
    },
    availability: {
      title: 'Disponibilité',
      subtitle: "Définissez les jours et heures d'ouverture de votre entreprise.",
      closed: 'Fermé',
      to: 'à',
      save: 'Enregistrer les horaires',
      saving: 'Enregistrement…',
      saved: '✓ Enregistré !',
      saveError: "Échec de l'enregistrement. Veuillez réessayer.",
      days: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    },
    services: {
      title: 'Services',
      subtitle: 'Définissez ce que vous proposez et la durée de chaque prestation.',
      add: '+ Ajouter un service',
      editTitle: 'Modifier le service',
      newTitle: 'Nouveau service',
      empty: 'Aucun service pour le moment',
      emptyHint: 'Ajoutez votre premier service pour commencer à recevoir des réservations.',
      nameLabel: 'Nom du service',
      namePlaceholder: 'Coupe & Coiffage',
      descLabel: 'Description (facultatif)',
      descPlaceholder: 'Une courte description pour vos clients…',
      durationLabel: 'Durée (minutes)',
      priceLabel: 'Prix (€)',
      saveChanges: 'Enregistrer',
      create: 'Créer le service',
      cancel: 'Annuler',
      edit: 'Modifier',
      remove: 'Supprimer',
      removeConfirm: 'Supprimer ce service ?',
      saving: 'Enregistrement…',
    },
    bookings: {
      title: 'Réservations',
      subtitle: 'Tous les rendez-vous clients de votre entreprise.',
      empty: 'Aucune réservation pour le moment',
      emptyHint: 'Partagez votre lien de réservation pour commencer à recevoir des rendez-vous.',
      all: 'tout',
      pending: 'en attente',
      confirmed: 'confirmé',
      cancelled: 'annulé',
      confirm: 'Confirmer',
      cancel: 'Annuler',
    },
    clientBookings: {
      empty: 'Aucune réservation pour le moment',
      emptyHint: 'Trouvez une entreprise et prenez votre premier rendez-vous.',
      bookAgain: 'Réserver à nouveau →',
    },
    billing: {
      title: 'Facturation',
      subtitle: 'Gérez votre abonnement et votre plan.',
      successBanner: 'Abonnement activé ! Votre plan a été mis à niveau vers Pro.',
      cancelledBanner: "Paiement annulé. Aucune modification n'a été apportée.",
      current: 'actuel',
      freeFeature1: '1 entreprise',
      freeFeature2: "Jusqu'à 50 réservations/mois",
      freeFeature3: 'Disponibilité de base',
      proFeature1: 'Réservations illimitées',
      proFeature2: 'Notifications par email',
      proFeature3: 'Support prioritaire',
      upgrade: 'Passer à Pro',
      manageBilling: 'Gérer la facturation',
      loadingBtn: 'Chargement…',
      cancelHint: 'Pour annuler ou modifier votre abonnement, utilisez le portail de facturation ci-dessus.',
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: 'Choisir un service',
      chooseDate: 'Choisir une date',
      chooseTime: 'Choisir un horaire',
      confirmBooking: 'Confirmer la réservation',
      back: '← Retour',
      today: "Aujourd'hui",
      min: 'min',
      checkingAvailability: 'Vérification des disponibilités…',
      noAvailability: 'Pas de disponibilité',
      tryAnotherDate: 'Essayez une autre date.',
      chooseAnotherDate: '← Choisir une autre date',
      notes: 'Notes (facultatif)',
      notesPlaceholder: "Informations pour l'entreprise…",
      signInNotice: 'Vous devrez vous connecter ou créer un compte pour confirmer cette réservation.',
      confirmBtn: 'Confirmer la réservation →',
      signInConfirmBtn: 'Se connecter et confirmer →',
      bookingInProgress: 'Réservation…',
      service: 'Service',
      date: 'Date',
      time: 'Heure',
      duration: 'Durée',
      total: 'Total',
      allBooked: 'Réservé !',
      bookAgain: 'Réserver à nouveau',
      viewMyBookings: 'Voir mes réservations →',
      bookedSoon: "L'entreprise confirmera votre rendez-vous prochainement.",
    },
    client: {
      hi: 'Bonjour,',
      upcomingBookings: 'Vos réservations à venir et passées.',
    },
  },

  es: {
    loading: 'Cargando…',
    viewBookingPage: '↗ Ver página de reservas',
    signOut: 'Cerrar sesión',
    tabs: {
      bookings: 'Reservas',
      services: 'Servicios',
      availability: 'Disponibilidad',
      billing: 'Facturación',
    },
    availability: {
      title: 'Disponibilidad',
      subtitle: 'Establezca los días y horarios en que su negocio acepta reservas.',
      closed: 'Cerrado',
      to: 'a',
      save: 'Guardar horario',
      saving: 'Guardando…',
      saved: '✓ ¡Guardado!',
      saveError: 'Error al guardar. Inténtelo de nuevo.',
      days: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    },
    services: {
      title: 'Servicios',
      subtitle: 'Defina lo que ofrece y cuánto tarda cada servicio.',
      add: '+ Añadir servicio',
      editTitle: 'Editar servicio',
      newTitle: 'Nuevo servicio',
      empty: 'Aún no hay servicios',
      emptyHint: 'Añada su primer servicio para empezar a recibir reservas.',
      nameLabel: 'Nombre del servicio',
      namePlaceholder: 'Corte & Peinado',
      descLabel: 'Descripción (opcional)',
      descPlaceholder: 'Una breve descripción para sus clientes…',
      durationLabel: 'Duración (minutos)',
      priceLabel: 'Precio (€)',
      saveChanges: 'Guardar cambios',
      create: 'Crear servicio',
      cancel: 'Cancelar',
      edit: 'Editar',
      remove: 'Eliminar',
      removeConfirm: '¿Eliminar este servicio?',
      saving: 'Guardando…',
    },
    bookings: {
      title: 'Reservas',
      subtitle: 'Todas las citas de clientes de su negocio.',
      empty: 'Aún no hay reservas',
      emptyHint: 'Comparta su enlace de reservas para empezar a recibir citas.',
      all: 'todas',
      pending: 'pendiente',
      confirmed: 'confirmada',
      cancelled: 'cancelada',
      confirm: 'Confirmar',
      cancel: 'Cancelar',
    },
    clientBookings: {
      empty: 'Aún no hay reservas',
      emptyHint: 'Encuentre un negocio y haga su primera cita.',
      bookAgain: 'Reservar de nuevo →',
    },
    billing: {
      title: 'Facturación',
      subtitle: 'Gestione su suscripción y plan.',
      successBanner: '¡Suscripción activada! Su plan ha sido actualizado a Pro.',
      cancelledBanner: 'Pago cancelado. No se realizaron cambios.',
      current: 'actual',
      freeFeature1: '1 negocio',
      freeFeature2: 'Hasta 50 reservas/mes',
      freeFeature3: 'Disponibilidad básica',
      proFeature1: 'Reservas ilimitadas',
      proFeature2: 'Notificaciones por email',
      proFeature3: 'Soporte prioritario',
      upgrade: 'Actualizar a Pro',
      manageBilling: 'Gestionar facturación',
      loadingBtn: 'Cargando…',
      cancelHint: 'Para cancelar o cambiar su suscripción, use el portal de facturación de arriba.',
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: 'Elegir un servicio',
      chooseDate: 'Elegir una fecha',
      chooseTime: 'Elegir un horario',
      confirmBooking: 'Confirmar reserva',
      back: '← Volver',
      today: 'Hoy',
      min: 'min',
      checkingAvailability: 'Comprobando disponibilidad…',
      noAvailability: 'Sin disponibilidad',
      tryAnotherDate: 'Pruebe otra fecha.',
      chooseAnotherDate: '← Elegir otra fecha',
      notes: 'Notas (opcional)',
      notesPlaceholder: 'Información para el negocio…',
      signInNotice: 'Se le pedirá que inicie sesión o cree una cuenta para confirmar esta reserva.',
      confirmBtn: 'Confirmar reserva →',
      signInConfirmBtn: 'Iniciar sesión y confirmar →',
      bookingInProgress: 'Reservando…',
      service: 'Servicio',
      date: 'Fecha',
      time: 'Hora',
      duration: 'Duración',
      total: 'Total',
      allBooked: '¡Reservado!',
      bookAgain: 'Reservar de nuevo',
      viewMyBookings: 'Ver mis reservas →',
      bookedSoon: 'El negocio confirmará su cita en breve.',
    },
    client: {
      hi: 'Hola,',
      upcomingBookings: 'Sus próximas reservas y las pasadas.',
    },
  },

  zh: {
    loading: '加载中…',
    viewBookingPage: '↗ 查看预约页面',
    signOut: '退出登录',
    tabs: {
      bookings: '预约',
      services: '服务',
      availability: '可用时间',
      billing: '账单',
    },
    availability: {
      title: '可用时间',
      subtitle: '设置您的业务接受预约的日期和时间。',
      closed: '关闭',
      to: '至',
      save: '保存时间表',
      saving: '保存中…',
      saved: '✓ 已保存！',
      saveError: '保存失败，请重试。',
      days: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
    },
    services: {
      title: '服务',
      subtitle: '定义您提供的服务及每项服务所需时间。',
      add: '+ 添加服务',
      editTitle: '编辑服务',
      newTitle: '新服务',
      empty: '暂无服务',
      emptyHint: '添加第一个服务以开始接受预约。',
      nameLabel: '服务名称',
      namePlaceholder: '剪发 & 造型',
      descLabel: '描述（可选）',
      descPlaceholder: '为客户提供简短描述…',
      durationLabel: '时长（分钟）',
      priceLabel: '价格（€）',
      saveChanges: '保存更改',
      create: '创建服务',
      cancel: '取消',
      edit: '编辑',
      remove: '删除',
      removeConfirm: '删除此服务？',
      saving: '保存中…',
    },
    bookings: {
      title: '预约',
      subtitle: '您业务的所有客户预约。',
      empty: '暂无预约',
      emptyHint: '分享您的预约链接以开始接受预约。',
      all: '全部',
      pending: '待确认',
      confirmed: '已确认',
      cancelled: '已取消',
      confirm: '确认',
      cancel: '取消',
    },
    clientBookings: {
      empty: '暂无预约',
      emptyHint: '找到一个商家并预约您的第一次服务。',
      bookAgain: '再次预约 →',
    },
    billing: {
      title: '账单',
      subtitle: '管理您的订阅和套餐。',
      successBanner: '订阅已激活！您的套餐已升级为 Pro。',
      cancelledBanner: '结账已取消。未做任何更改。',
      current: '当前',
      freeFeature1: '1 个商家',
      freeFeature2: '每月最多 50 次预约',
      freeFeature3: '基本可用时间',
      proFeature1: '无限预约',
      proFeature2: '邮件通知',
      proFeature3: '优先支持',
      upgrade: '升级到 Pro',
      manageBilling: '管理账单',
      loadingBtn: '加载中…',
      cancelHint: '如需取消或更改订阅，请使用上方的账单门户。',
    },
    booking: {
      poweredBy: 'Schedully',
      chooseService: '选择服务',
      chooseDate: '选择日期',
      chooseTime: '选择时间',
      confirmBooking: '确认预约',
      back: '← 返回',
      today: '今天',
      min: '分钟',
      checkingAvailability: '检查可用性…',
      noAvailability: '无可用时间',
      tryAnotherDate: '请尝试其他日期。',
      chooseAnotherDate: '← 选择其他日期',
      notes: '备注（可选）',
      notesPlaceholder: '给商家的信息…',
      signInNotice: '您需要登录或创建账户以确认预约。',
      confirmBtn: '确认预约 →',
      signInConfirmBtn: '登录并确认 →',
      bookingInProgress: '预约中…',
      service: '服务',
      date: '日期',
      time: '时间',
      duration: '时长',
      total: '合计',
      allBooked: '预约成功！',
      bookAgain: '再次预约',
      viewMyBookings: '查看我的预约 →',
      bookedSoon: '商家将很快确认您的预约。',
    },
    client: {
      hi: '你好，',
      upcomingBookings: '您即将到来的和过去的预约。',
    },
  },
};

export type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: translations.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
